// site-config.js
// Generated by unify-app-test/tools/generate-phase2-config.mjs

(function () {
  const SiteConfig = {
      "SITE_NAME": "Rule 34",
      "POPUP_TITLE": "Downloader for Rule 34",
      "OFFSCREEN": {
          "downloadFolder": "Rule 34",
          "defaultRefererUrl": "https://rule34.world/",
          "defaultOrigin": "https://rule34.world",
          "readyTypes": [
              "Rule34_OFFSCREEN_READY"
          ],
          "fetch": {
              "includeOriginHeader": true
          },
          "hls": {
              "mode": "transmux",
              "completion": "offscreen",
              "continueOnSegmentError": true,
              "maxSegmentRetries": 3,
              "backoffBaseMs": 500,
              "stallTimeoutMs": 30000
          },
          "mp4": {
              "completion": "offscreen",
              "revokeDelayMs": 15000
          }
      },
      "PLAYER_BUTTON": {
          "mode": "single-video",
          "classPrefix": "rule34",
          "cssId": "rule34-player-button-css",
          "attachAttr": "data-rule34-dl-attached",
          "applyThemeVars": true,
          "selectors": {
              "container": [
                  "#player",
                  ".mainPlayerDiv",
                  ".video-player",
                  ".video-info",
                  ".video-platform",
                  ".plyr"
              ],
              "video": [
                  "video.v-player",
                  ".video-player video",
                  "video"
              ],
              "videoClosest": [
                  ".video-player, .video-info, .video-platform, .plyr"
              ]
          },
          "videoInfo": {
              "requiredAny": [
                  "id"
              ]
          }
      },
      "BACKGROUND": {
          "contextMenu": {
              "id": "download-rule34-video",
              "title": "Download Rule 34 Video",
              "contexts": [
                  "page",
                  "video"
              ],
              "documentUrlPatterns": [
                  "https://rule34.world/*",
                  "https://*.rule34.world/*",
                  "http://rule34.world/*",
                  "http://*.rule34.world/*",
                  "https://www.rule34.world/*",
                  "http://www.rule34.world/*",
                  "https://rule34video.com/*",
                  "https://*.rule34video.com/*",
                  "http://rule34video.com/*",
                  "http://*.rule34video.com/*"
              ],
              "messageAction": "getVideoInfo"
          },
          "offscreenDocument": {
              "reasons": [
                  "DOM_SCRAPING"
              ],
              "justification": "Process HLS video streams and create downloadable files",
              "logMessage": "Creating offscreen document for HLS processing"
          }
      },
      "UPDATE_CHECK": {
          "enabled": true,
          "provider": "github-releases",
          "repoOwner": "freeforall1932-design",
          "repoName": "rule34video",
          "checkIntervalMs": 21600000,
          "requestTimeoutMs": 8000,
          "releaseApiUrl": "https://api.github.com/repos/freeforall1932-design/rule34video/releases/latest",
          "releasePageUrl": "https://github.com/freeforall1932-design/rule34video/releases/latest"
      },
      "LOG_LEVEL": "debug",
      "LOG_MIRROR_TO_BG": true,
      "COLORS": {
          "brandAccent": "#2563eb",
          "brandAccentHover": "#1d4ed8",
          "bgDark": "#131722",
          "bgDarker": "#1b2230",
          "borderDark": "#2a3345",
          "inputBorder": "#3a465e",
          "textPrimary": "#f8fafc",
          "textSubtle": "#cbd5e1",
          "textMuted": "#94a3b8",
          "success": "#22c55e",
          "error": "#ef4444",
          "info": "#38bdf8",
          "lightBorder": "#cbd5e1",
          "lightBg": "#e2e8f0"
      },
      "ADAPTER": {
          "staticMediaUrls": [],
          "preferredMediaUrlPatterns": [],
          "blockedMediaUrlPatterns": [
              "roomad",
              "notifications?",
              "gambling",
              "bonus",
              "/ads?/",
              "/ad/",
              "banner",
              "thumbs?",
              "thumbnails?",
              "preview",
              "sprite",
              "logo",
              "\\.gif(?:[?#]|$)"
          ],
          "selectors": {
              "title": [
                  "meta[property=\"og:title\"]",
                  "h1",
                  ".title",
                  "title"
              ],
              "video": [
                  "video[src]",
                  "video source[src]",
                  "source[src]",
                  "meta[property=\"og:video\"]",
                  "meta[property=\"og:video:secure_url\"]",
                  "meta[name=\"twitter:player:stream\"]"
              ],
              "thumbnail": [
                  "meta[property=\"og:image\"]",
                  "video[poster]"
              ]
          }
      }
  };

  function toCssVarName(colorKey = "") {
    return String(colorKey)
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/_/g, "-")
      .toLowerCase();
  }

  function applyThemeVariables(
    doc = typeof document !== "undefined" ? document : null,
    colors = SiteConfig.COLORS,
    styleId = "site-theme-vars",
  ) {
    if (!doc) return;
    try {
      if (doc.getElementById(styleId)) return;
      const styleElement = doc.createElement("style");
      styleElement.id = styleId;
      const cssVars = Object.entries(colors || {})
        .filter(([, value]) => value !== undefined && value !== null && String(value) !== "")
        .map(([key, value]) => `--${toCssVarName(key)}:${String(value)};`)
        .join("\n        ");
      styleElement.textContent = `:root{\n        ${cssVars}\n      }`;
      (doc.head || doc.documentElement).appendChild(styleElement);
    } catch {}
  }

  try {
    globalThis.SiteConfig = SiteConfig;
  } catch {}

  try {
    if (typeof document !== "undefined") {
      applyThemeVariables(document, SiteConfig.COLORS, "site-theme-boot-vars");
    }
  } catch {}
  try {
    globalThis.applySiteThemeVariables = applyThemeVariables;
  } catch {}
  try {
    globalThis.applyRule34ThemeVariables = applyThemeVariables;
  } catch {}
  try {
    applyThemeVariables();
  } catch {}
})();
